version: "3"
services:
  feedback-api:
    image: ghcr.io/jitsi-hd/feedback-api:latest
    build:
      context: .
    restart: always
    environment:
      - NODE_ENV
    volumes:
      - "./data:/home/node/data"
    expose:
      - 3000
